export const ADD_WEBTOON = 'ADD_WEBTOON';
export const EDIT_WEBTOON = 'EDIT_WEBTOON';
export const DELETE_WEBTOON = 'DELETE_WEBTOON';
export const UPDATE_WEBTOON = 'UPDATE_WEBTOON';

export const ADD_EPISODE = 'ADD_EPISODE';
export const EDIT_EPISODE = 'EDIT_EPISODE';
export const UPDATE_EPISODE = 'UPDATE_EPISODE';
export const DELETE_EPISODE = 'DELETE_EPISODE';

export const DELETE_IMAGE_EPISODE = 'DELETE_IMAGE_EPISODE';
export const ADD_IMAGE_EPISODE = 'ADD_IMAGE_EPISODE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
