export const ADD_MY_WEBTOON = 'ADD_MY_WEBTOON';
export const DELETE_MY_WEBTOON = 'DELETE_MY_WEBTOON';
export const UPDATE_MY_WEBTOON = 'UPDATE_MY_WEBTOON';
export const GET_MY_WEBTOON = 'GET_MY_WEBTOON';

export const ADD_MY_EPISODE = 'ADD_MY_EPISODE';
export const UPDATE_MY_EPISODE = 'UPDATE_MY_EPISODE';
export const DELETE_MY_EPISODE = 'DELETE_MY_EPISODE';
export const GET_MY_EPISODE = 'GET_MY_EPISODE';

export const GET_MY_EPIDOSE_IMAGE = 'GET_MY_EPIDOSE_IMAGE';

export const DELETE_IMAGE_EPISODE = 'DELETE_IMAGE_EPISODE';
export const ADD_IMAGE_EPISODE = 'ADD_IMAGE_EPISODE';

export const GET_ALL_WEBTOON = 'GET_ALL_WEBTOON';
export const GET_ALL_EPISODE = 'GET_ALL_EPISODE';
export const GET_ALL_IMAGE_EPISODE = 'GET_ALL_IMAGE_EPISODE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
